### ISSUE TITLE
Add Pyramid Patterns | C#

### ISSUE THREAD

**Issue by aryashah2k** [aryashah2k/Printing-Pattern-Programs#44]

**Comment by arun-jain-dev** [comment]
@aryashah2k  Since none of the contributors have taken up the C# Section of this repository and I have some experience in this language, I could work for the complete section of C#. 
You can assign me all the issues for C# Patterns and I promise I can complete them as soon as possible. Its been a long time since I have practiced such programs using C# so this would help me master the language a bit too imo.

**Comment by arun-jain-dev** [comment]
@aryashah2k  Since none of the contributors have taken up the C# Section of this repository and I have some experience in this language, I could work for the complete section of C#. 
You can assign me all the issues for C# Patterns and I promise I can complete them as soon as possible. Its been a long time since I have practiced such programs using C# so this would help me master the language a bit too imo.

**Comment by arun-jain-dev** [comment]
@aryashah2k  Since none of the contributors have taken up the C# Section of this repository and I have some experience in this language, I could work for the complete section of C#. 
You can assign me all the issues for C# Patterns and I promise I can complete them as soon as possible. Its been a long time since I have practiced such programs using C# so this would help me master the language a bit too imo.

**Comment by arun-jain-dev** [comment]
@aryashah2k PR created successfully for this issue

**Comment by aryashah2k** [comment]
Hey @arun-jain-dev , I've reviewed your work and successfully merged the PR ! Thanks for the contributions. Youve done a great job for the C# Section of this repository.
