### ISSUE TITLE
Add Numeric Patterns | C#

### ISSUE THREAD

**Issue by aryashah2k** [aryashah2k/Printing-Pattern-Programs#45]

**Comment by arun-jain-dev** [comment]
@aryashah2k  Since none of the contributors have taken up the C# Section of this repository and I have some experience in this language, I could work for the complete section of C#. 
You can assign me all the issues for C# Patterns and I promise I can complete them as soon as possible. Its been a long time since I have practiced such programs using C# so this would help me master the language a bit too imo.

**Comment by aryashah2k** [comment]
PR for Issue successfully merged. Credits to @arun-jain-dev

**Comment by aryashah2k** [comment]
@arun-jain-dev , I just checked the PR for this issue, it seems you have added the wrong files since all of them are empty! Please rectify this error and add files with code inside.

**Comment by arun-jain-dev** [comment]
Oh my god I'm so sorry I never realized this. I have rectified my mistakes and created the fresh PRs with files that are not empty and have all the code inside. I guess I might have pushed all the files from my old directory where all the files were empty and served as a template for all the pattern programs.
Please accept the apology and merge the PRs with all the completed patterns!

**Comment by aryashah2k** [comment]
It's alright buddy I'm glad that you rectified it quickly, Im closing this issue and have merged the PR by then.
Again I would thank you for all your contributions. You single handedly managed writing code for the C# Section which has tremendously helped this repository.
All the best,
Arya
