### ISSUE TITLE
Add Symbol Patterns | C#

### ISSUE THREAD

**Issue by aryashah2k** [aryashah2k/Printing-Pattern-Programs#47]

**Comment by arun-jain-dev** [comment]
@aryashah2k  Since none of the contributors have taken up the C# Section of this repository and I have some experience in this language, I could work for the complete section of C#. 
You can assign me all the issues for C# Patterns and I promise I can complete them as soon as possible. Its been a long time since I have practiced such programs using C# so this would help me master the language a bit too imo.

**Comment by aryashah2k** [comment]
Sure @arun-jain-dev  Thanks for taking this initiative. I might trust you with the responsibility of the complete C# Section since none of us have experience with this language. Take your time and help complete the C# Section of the repository
All the Best!

**Comment by aryashah2k** [comment]
PR Successfully merged for this issue
